malloydata/malloy-py

src/malloy/data/bigquery/bq_connection.py, tests/malloy/data/bigquery/test_bq_connection.py
Allow for records, arrays and json fields.
Additionally manually test with:
```python
model = runtime.load_source("""
source:ga_sessions is table('bigquery:malloy-data.malloytest.ga_sample'){
measure:
user_count is count(distinct fullVisitorId)
percent_of_users is user_count/all(user_count)*100
session_count is count()
total_visits is totals.visits.sum()
total_hits is totals.hits.sum()
total_page_views is totals.pageviews.sum()
t2 is totals.pageviews.sum()
total_productRevenue is hits.product.productRevenue.sum()
hits_count is hits.count()
sold_count is hits.count() { where: hits.product.productQuantity > 0 }
}
""")
data = await model.run("bigquery", """
query: ga_sessions -> {
where: trafficSource.source != '(direct)'
group_by: trafficSource.source
aggregate:
user_count
percent_of_users …
```
=> Fill out bigquery types some more

.gitmodules, README.md, cloudbuild/test/cloudbuild.yaml, scripts/gen-protos.sh, scripts/gen-services.sh
This should make it easier to coordinate changes with the service.
=> Add malloy-service as a submodule

src/malloy/data/duckdb/duckdb_connection.py, tests/malloy/data/duckdb/test_duckdb_connection.py
Add structures and arrays, add tests for unsupported type as well.
=> Add more duckdb types

src/malloy/ipython/ipython_magic.py, src/malloy/runtime.py, src/malloy/services/v1/compiler_pb2.py, src/malloy/services/v1/compiler_pb2.pyi, tests/malloy/ipython/test_data/test.ipynb, tests/malloy/test_runtime.py
Run Query now renders the HTML result in the result area.
Notebook can be run in COMPILE_AND_RENDER or COMPILE_ONLY mode using NOTEBOOK_MODE flag.
NOTEBOOK_MODE="COMPILE_ONLY"
=> Compile and Render in malloy-py

cloudbuild/test/cloudbuild.yaml
Make our cloud build steps less opaque.
=> Add ids to cloud build steps

src/malloy/runtime.py, tests/malloy/ipython/test_data/test.ipynb
We were reporting "No results" instead of the actual error.
=> Fix error reporting

src/malloy/ipython/ipython_magic.py
Bad arguments used to cause a stack trace and attempt to exit the runtime, now they simply print an error message.
=> Better argument error messages

src/malloy/data/__init__.py, src/malloy/data/schema_cache.py, src/malloy/runtime.py, tests/malloy/data/test_schema_cache.py
Cache table schemas for each connection.
=> Schema cache

cloudbuild/publish-github/cloudbuild.yaml, requirements.dev.txt, scripts/do-github-release.py
Add scripts for building and publishing malloy-py packages to github.
=> Add github release scripts

src/malloy/runtime.py
Don't try to parse model if there is none.
=> Better handle model errors

cloudbuild/publish-github/cloudbuild.yaml
Remove asyncio.run() since gen_requirements_file() is not async, just the output method is.
=> Remove asyncio call, generation wasn't async.

tests/malloy/test_data/test_file_01.malloy
Fix license header, should be MIT not GPL
=> Fix license header

src/malloy/runtime.py, tests/malloy/ipython/test_data/test.ipynb
Increase grpc message size.
Fix service mode defaut.
=> Increase GRPC message size

cloudbuild/publish-pypi/cloudbuild.yaml
Update command for twine upload to PyPI
=> Update twine call format

src/malloy/ipython/ipython_magic.py, src/malloy/ipython/tab_renderer.py, src/malloy/runtime.py, tests/malloy/test_runtime.py
https://github.com/malloydata/malloy-py/issues/83
=> Make the tabbed results similar to MalloyDocs.

src/malloy/data/bigquery/bq_connection.py
Adds malloy user agent, includes malloy version and python version.
=> Add malloy user_agent.

requirements.dev.txt, tests/malloy/data/bigquery/test_bq_connection.py
Add tests for big query.
Setup so that the tests are skipped automatically if BQ is not configured
=> Add e2e big query test

cloudbuild/publish-pypi/cloudbuild.yaml, pyproject.toml
Add step to also upload the final release to github, this will have all the changes rollup into the changelog since the last final release to github. 
*First release will contain all the previous changes, but subsequent ones should contain a more useful list with only changes for that release.
=> Update PyPI publish to add link to release notes.

MANIFEST.in, src/malloy/ipython/ipython_magic.py, src/malloy/ipython/tab_renderer.py, src/malloy/runtime.py, src/malloy/services/v1/compiler_pb2.py, src/malloy/services/v1/compiler_pb2.pyi, tests/malloy/test_runtime.py
Needs https://github.com/malloydata/malloy-service/pull/34 merged to work.
Includes the bundled renderer from https://github.com/malloydata/malloy/pull/1579.
=> include bundled renderer

.github/workflows/test.yaml, cloudbuild/publish-github/cloudbuild.yaml, cloudbuild/publish-pypi/cloudbuild.yaml, scripts/gen-snowflake-auth.sh, tests/malloy/test_runtime.py
Make the Snowflake connection config one secret so that forks can define their own test connections.
=> Snowflake config
